import type { Metadata } from "next";
import { Geist, Cookie, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/page";

const cookie = Cookie({
  variable: "--font-cookie",
  subsets: ["latin"],
  weight: "400",
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cookie.variable} ${roboto.className} antialiased relative bg-slate-100 text-gray-800 tracking-tight`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
